name: Revert, Comment, and Mirror Contributors

on:
  pull_request_target:
    types:
      - closed
  push:
    paths:
      - 'README.md'
  issues:
    types:
      - opened

jobs:
  auto-revert:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_target' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login != 'dependabot[bot]' &&
      github.event.pull_request.user.login != 'nikohoffren' &&
      github.event.pull_request.user.login != 'dependabot-preview[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Revert merge commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git revert -m 1 HEAD
          git push origin main

  comment:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_target' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login != 'dependabot[bot]' &&
      github.event.pull_request.user.login != 'dependabot-preview[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_PAT }}
      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.REPO_PAT }}"
      - name: Comment on PR
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "## Merged

          > This is an automated message from Fork, Commit, Merge [BOT].

          Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

          ### What's next?

          If you're looking for more ways to contribute, I invite you to check out our [forkcommitmerge.io](https://github.com/fork-commit-merge/fork-commit-merge-web) website repository. The repository contain real issues that you can help to resolve or create some of your own if you see any bugs or want to add new features to the site, etc. You can also check out the [Influences](https://github.com/fork-commit-merge/fork-commit-merge#influences) section in the README to find more projects similar to this one.

          Also please leave a star to this project if you feel it helped you, i would really appreciate it.

          I look forward to seeing your contributions!"

  add-contributor-to-readme:
    needs: auto-revert
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_target' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.user.login != 'dependabot[bot]' &&
      github.event.pull_request.user.login != 'dependabot-preview[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0

      - name: Reset to the latest main
        run: |
          git fetch origin
          git reset --hard origin/main

      - name: Add contributor to README
        run: |
          if ! grep -q "${{ github.event.pull_request.user.login }}" README.md
          then
            echo "<a href=\"https://github.com/${{ github.event.pull_request.user.login }}\"><img src=\"https://images.weserv.nl/?url=https://avatars.githubusercontent.com/u/${{ github.event.pull_request.user.id }}?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d\" width=\"80px\"/></a>" >> README.md
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "Add ${{ github.event.pull_request.user.login }} to contributors list"
            git push
          fi
        env:
          GH_TOKEN: ${{ secrets.REPO_PAT }}
          GH_REPO: ${{ github.repository }}

  sync-contributors:
    needs: add-contributor-to-readme
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_PAT }}
        fetch-depth: 0

    - name: Extract last contributor
      id: extract_last_contributor
      run: |
        LAST_CONTRIBUTOR=$(tail -n 1 README.md | awk -F'[@"]' '{print $2}')
        echo "::set-output name=last_contributor::$LAST_CONTRIBUTOR"

    - name: Debug
      run: echo "Last contributor is ${{ steps.extract_last_contributor.outputs.last_contributor }}"

    - name: Get contributor id
      id: get_contributor_id
      run: |
        ID=$(curl -s -H "Authorization: token ${{ secrets.REPO_PAT }}" "https://api.github.com/users/${{ steps.extract_last_contributor.outputs.last_contributor }}" | grep '"id":' | sed 's/[^0-9]//g')
        echo "::set-output name=contributor_id::$ID"

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: 'nikohoffren/fork-commit-merge-web'
        token: ${{ secrets.REPO_PAT }}
        path: 'fork-commit-merge-web'

    - name: Add contributors to components/data/contributorData.ts
      run: |
        CONTRIBUTOR_LOGIN="${{ steps.extract_last_contributor.outputs.last_contributor }}"
        CONTRIBUTOR_ID="${{ steps.get_contributor_id.outputs.contributor_id }}"
        echo "Adding contributor: $CONTRIBUTOR_LOGIN with ID: $CONTRIBUTOR_ID"
        echo "<a href=\"https://github.com/$CONTRIBUTOR_LOGIN\"><img src=\"https://images.weserv.nl/?url=https://avatars.githubusercontent.com/u/$CONTRIBUTOR_ID?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d\" width=\"80px\"/></a>" >> fork-commit-merge-web/components/data/contributorData.ts

    - name: Commit and push to fork-commit-merge-web
      run: |
        cd fork-commit-merge-web
        git config user.name "nikohoffren"
        git config user.email "niko.hoffren@gmail.com"
        git add components/data/contributorData.ts
        git commit -m "Sync contributors from fork-commit-merge"
        git push

  label-new-issue:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Add labels to new issue
        run: |
          issue_number=${{ github.event.issue.number }}
          labels='["first-contributor","first-contributors","good first issue","help wanted","up-for-grabs"]'

          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.REPO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/labels" \
            -d "{ \"labels\": $labels }"
